#include <xc.h>
#include <p32xxxx.h>
#include <plib.h>
#include <peripheral/spi.h>

#include "pmodsf.h"

#define SPI_PRI     2
#define SPI_SUBPRI  0

void __ISR(_SPI_4_VECTOR, IPL2AUTO) spi_handler(void)
{
    // check if the interrupt was generated by transmit
    if (IFS1bits.SPI4TXIF){
        // process transmit interrupt
    }
    
    // check if interrupt was generated by receive
    if (IFS1bits.SPI4RXIF){
        // process receive interrupt
    }
    
    // check if interrupt was generated by error
    if (IFS1bits.SPI4EIF){
        // process error interrupt
    }
    
    // clear receive, transmit, and error interrupt status bits for SPI4 module
    IFS1bits.SPI4TXIF = 0;
    IFS1bits.SPI4RXIF = 0;
    IFS1bits.SPI4EIF = 0;
    
    return;
}

void initialize_spi()
{
    SPI4CON = 0; // turn off SPI module 4
    uint8_t junk = SPI4BUF;
    
    // clear receive, transmit, and error interrupt status bits for SPI4 module
    IFS1bits.SPI4TXIF = 0;
    IFS1bits.SPI4RXIF = 0;
    IFS1bits.SPI4EIF = 0;
    
    // clear previous interrupt priority and subpriority for SPI4 module
    IPC8bits.SPI4IP = 0x0;
    IPC8bits.SPI4IS = 0x0;
    
    // set interrupt priority and subpriority for SPI4 module
    IPC8bits.SPI4IP = SPI_PRI;
    IPC8bits.SPI4IS = SPI_SUBPRI;
    
    // turn on transmit, receive, and error interrupts for SPI4 module
    IEC1bits.SPI4TXIE = 1;
    IEC1bits.SPI4RXIE = 1;
    IEC1bits.SPI4EIE = 1;
    
    // set up the buffer for SPI4 module
    SPI4BRG = 0x01; // set BRG for SPI4
    SPI4STATbits.SPIROV = 0; // clear Receive Overflow Flag for SPI4 module
    
    // set up SPI4 module control bits
    SPI4CONbits.SMP = 1;    // input data sampled at end of data output time
    SPI4CONbits.MSTEN = 1;  // put SPI4 module into master mode 
    SPI4CONbits.ON = 1;     // turn on SPI4 module
    
    return;
}